### ISSUE TITLE
How to get the Graph?

### ISSUE THREAD

**Issue by FaserF** [MarcHagen/weather-card#3]
Thanks for your fork. I love the animated weather card an was searching exactly for this with a graph.
Unfortunatly I am unable to get the Graph with your Frontend Integration.
You havent documented, If there is anything specific to activate the graph?

I have set up it the same way like I did with the orignal weather-card, but I wont get a graph. It just looks the same like the original weather Card integration from bramkragten

Any help would be apreciated.

**Comment by MarcHagen** [comment]
Hi!

The graph isn't enabled by default.
If you specify `graph: true` it should come-up

**Comment by FaserF** [comment]
Here is my now used code:

`type: vertical-stack
cards:
  - type: 'custom:weather-card'
    entity: weather.dwd_weather_location_1h
    hourly_forecast: true
    number_of_forecasts: '6'
    graph: true
  - type: 'custom:weather-card'
    entity: weather.dwd_weather_location
    number_of_forecasts: '5'
    hourly_forecast: false
    current: false
    details: false
    forecast: true
`

but still both look the same with no Graph being shown.
![E80BEA7F-D6DF-4295-B88D-380AF52B1EA9](https://user-images.githubusercontent.com/12374134/119854569-74ceef00-bf11-11eb-9883-fe109736de57.png)


background info:
I was running the original animated weather card before.

Can this still be some caching issue?

**Comment by MarcHagen** [comment]
Maybe
I'll check your config on my install see if i can spot the error.

**Comment by FaserF** [comment]
After starting HA in an incognito tab and trying to clear the cache the full widget went away. I can see it when I choose "edit" but its just empty, even in the preview.

**Comment by MarcHagen** [comment]
Yep i see the same problem. HA changed some frontend stuff and it's not working anymore.
Gives me a good excuse to update the card :)

**Comment by MarcHagen** [comment]
Hi i've fixed the bug in the latest release, could you please update your version and check if you have any issues?

**Comment by FaserF** [comment]
It is working again! Thank you.
