### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by Ariosinm** [MarcHagen/weather-card#4]
While trying to install this card using the dist/weather-card.js file in storage mode, the card in lovelace showed the error “_Failed to fetch dynamically imported module_”. Investigating the changes since the 1.6.5 update I was able to find that the weather-card-editor.js file is no longer present, even though it is the one listed in the readme for manual installation in storage mode.

![image](https://github.com/MarcHagen/weather-card/assets/114727908/20925a9f-1e41-4435-b171-b6a7dbb407a4)

Could this have been an upgrade error or am I just doing something wrong?

**Comment by MarcHagen** [comment]
I've found that the link in the readme was pointing to the 1.5.0 release, which is a old version.
if you have downloaded that, please download the latest release zip or the `weather-card.js` from `dist`.

The `weather-card-editor.js` is indeed no longer needed as a separate file; it is all in the `weather-card.js` since 1.7.0

I believe the current version is not working with the newer version(s) of HA. At least it is not loading for me at the moment. I'm looking at what is needed to update the code to get it working again.

If your instance is working, please also let me know!

**Comment by MarcHagen** [comment]
Ah yes so the the forecast attribute has been removed from WeatherEntity
https://github.com/home-assistant/core/pull/110761

So i need to update the card to get it working again.

**Comment by MarcHagen** [comment]
Version 1.8.0 should work fine again.
Please consider HACS, else update your instance from the dist folder.

**Comment by Ariosinm** [comment]
Hi again Marc, thank you for all of your effort!! The car now works, but I think there is some kind of bug, because of when I select the graph, any graph is displayed :(

![image](https://github.com/MarcHagen/weather-card/assets/114727908/440bbf07-5f61-4cf9-ba8f-1619f022e62a)

This is the config of the card:

`card_config_version: 2`
`mode: hourly`
`current: true`
`details: true`
`entity_weather: weather.forecast_casa`
`forecast: true`
`icons: /local/weather-card/icons/animated/`
`type: custom:weather-card`
`graph: true`
`hidePrecipitation: false`

**Comment by MarcHagen** [comment]
Yep you are absolutely right, I'm seem to also have this... it was working tho haha. Sad. But I have changed more stuff which apparently broke it .

I'll recheck the code and push an fix when I have one.

**Comment by Ariosinm** [comment]
Thxx for your quick answer, I'll be looking for the update, your card is cool as f haha. If you need more testing, always happy to help :)

**Comment by MarcHagen** [comment]
Hi! Took me a bit, Hass had updated the chart.js library which broke quite a bit due to the major upgrade from 3.x to 4.x.
Chart it working again, also update some other parts.

**Comment by Ariosinm** [comment]
Hi Mark, thanks for the hard work! I have downloaded version 1.8.1 and now I can see the sun entity values and icons, but I can't see the graph even though I have enabled it.

![image](https://github.com/MarcHagen/weather-card/assets/114727908/cebcfc89-6cd6-46f2-bfd4-f9b9a4003f2d)

`type: custom:weather-card`
`entity_weather: weather.forecast_casa`
`entity_sun: sun.sun`
`mode: hourly`
`current: true`
`details: true`
`forecast: true`
`forecastMaxColumn: 5`
`icons: /local/weather-card/icons/animated/`
`graph: true`
`hidePrecipitation: false`
`card_config_version: 2`

Am I doing anything wrong or is the issue still present somehow? Thanks for all the effort you're putting into this :))

**Comment by Ariosinm** [comment]
PS I had to manually add the  `mode: hourly` and `entity_sun: sun.sun` becasue visual editor althoug I was setting the values, wasn't updating the code :(

**Comment by Ariosinm** [comment]
Hi again Marc, this morning the card is working flawlessly without touching anything. Thank you for your patience and sorry for the inconvenience my comments may had casued

**Comment by MarcHagen** [comment]
Never any inconvenience 👌🏻
